#!/usr/bin/python
"""
 Copyright (C) 2024 boogie

 This program is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with this program.  If not, see <http://www.gnu.org/licenses/>.
"""
import argparse
import os
import sys
import logging

from smccc import common
from smccc import log
from smccc.implementations.rockchip import dmc


parser = argparse.ArgumentParser(prog="rktune")
parser.add_argument("--debug", "-d", action='store_true', help="enable debug logging")
subparsers = parser.add_subparsers(help="command", dest="command", required=True)


parser_mem = subparsers.add_parser('mem', help="memory tuning")
subparsers_mem = parser_mem.add_subparsers(help="sub command", dest="subcommand", required=True)
parser_mem_setclock = subparsers_mem.add_parser('setclock', help="set current dram clock")
parser_mem_setclock.add_argument("clock", type=int, help="clock frequency in Mhz")

args = parser.parse_args()

if not os.path.exists(common.PROCPATH):
    log.logger.error(f"{common.PROCPATH} device does not exists. Please load the kernel module with 'insmod smccc.ko'")
    sys.exit(-1)

if not os.access(common.PROCPATH, os.R_OK):
    log.logger.error(f"{common.PROCPATH} device is not readable. Run as root or give proper permissions to {common.PROCPATH}")
    sys.exit(-2)

if not os.access(common.PROCPATH, os.W_OK):
    log.logger.error(f"{common.PROCPATH} device is not writable. Run as root or give proper permissions to {common.PROCPATH}")
    sys.exit(-3)

if args.debug:
    log.setlevel(logging.DEBUG)
if args.command == "mem":
    with dmc.Dram() as dram:
        if args.subcommand == "setclock":
            resp = dram.setclock(args.clock)
            if(not resp):
                log.logger.info(f"Dram clock is set to {args.clock}Mhz")
            else:
                log.logger.info(f"Can not set dram clock")
                sys.exit(resp)
